version: '3.1'
networks:
    laravel_dockerized:
        driver: bridge
services:
    nginx:
        image: nginx:latest
        container_name: ${APP_NAME}_nginx
        ports:
            - ${APP_PORT}:80
        volumes:
            - ./:/var/www/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
        restart: always
        networks:
            - laravel_dockerized
    php-fpm:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: ${APP_NAME}_php
        restart: always
        tty: true
        #pid: "host"
        volumes:
            - ./:/var/www/html
        depends_on:
            - mariadb
        networks:
            - laravel_dockerized
    mariadb:
        image: mariadb:10.10
        container_name: ${APP_NAME}_mariadb
        restart: unless-stopped
        ports:
            - ${DB_PORT}:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - .docker/mariadb/data:/var/lib/mysql
        networks:
            - laravel_dockerized
    redis:
        image: redis:alpine
        container_name: ${APP_NAME}_redis
        restart: unless-stopped
        ports:
            - ${REDIS_PORT}:6379
        volumes:
            - .docker/redis/config/:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
        networks:
            - laravel_dockerized
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${APP_NAME}_phpmyadmin
        links:
            - mariadb:mariadb
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            MYSQL_USERNAME: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            PMA_HOST: mariadb
        depends_on:
            - mariadb
        networks:
            - laravel_dockerized
    cronjob:
        container_name: ${APP_NAME}_cronjob
        build:
            context: .
            dockerfile: .docker/cronjob/Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - ${CRONJOB_PORT}:80
        #pid: container:${APP_NAME}_php
        depends_on:
            - php-fpm
            - mariadb
        restart: always
    jenkins:
        container_name: ${APP_NAME}_jenkins
        image: jenkins/jenkins:lts
        ports:
        - "${JENKINS_PORT}:8080"
        volumes:
        - .docker/jenkins/jenkins_home:/var/jenkins_home

    # jenkins:
    #     container_name: ${APP_NAME}_jenkins
    #     build:
    #         context: .
    #         dockerfile: .docker/jenkins/Dockerfile
    #     ports:
    #     - "${JENKINS_PORT}:8080"
    #     volumes:
    #     - .docker/jenkins/jenkins_home:/var/jenkins_home
